### ISSUE TITLE
Add option to change commands

### ISSUE THREAD

**Issue by LittleHuba** [I-Dream-in-Code/kde-arch-update-plasmoid#2] opened 2017-10-11 16:03 UTC
Please add an option where you can change the commands that are run when checking for updates and upgrading your system.

**Comment by I-Dream-in-Code** [comment] 2017-10-11 16:31
What type of commands?

I'm not including all of them.

Why should I add commands?

It does what it's supposed to do just fine

**Comment by LittleHuba** [comment] 2017-10-11 17:27
For example to support pacaur or yaourt and provide support for the AUR-Repositories? You could just provide textinputs where one can edit the commands. The Gnome plugin does just that.

**Comment by LittleHuba** [comment] 2017-10-11 17:30
Here is the repo of the Gnome plugin I mentioned above. The link directs you to the wiki page of the repo where the commands are explained.

https://github.com/RaphaelRochet/arch-update/wiki

**Comment by I-Dream-in-Code** [comment] 2017-10-11 17:41
See issue #1 for yaourt and aur support

I'll look into gnome

**Comment by I-Dream-in-Code** [comment] 2017-10-11 17:56
The only viable option is yaourt only

Should it be a setting or default aur support without an option to do non aur?

**Comment by LittleHuba** [comment] 2017-10-11 18:12
Why would pacaur be not an option?

**Comment by I-Dream-in-Code** [comment] 2017-10-11 18:37
Like I said before

What I don't want is everyone suggesting their favorite aur helper of choice.

I need to have it return `checkupdates` style format that shows the package name, current version and new version

`yaourt -Qua` does that for sure

**Comment by LittleHuba** [comment] 2017-10-11 18:49
You could add a dependency to `checkupdates-aur` which provides the same service as checkupdates but for the AUR-Repositories. Then it would only be necessary to provide a textinput for the command to upgrade.

And to get back to your question about the additional option: More options for the user do not hurt, so go along with providing the option.

**Comment by I-Dream-in-Code** [comment] 2017-10-11 19:07
duplicate of #1

**Comment by I-Dream-in-Code** [comment] 2017-10-11 19:08
That is a good alternative it seems but it's having issues building on my machine I'll look into it

**Comment by I-Dream-in-Code** [comment] 2017-10-11 19:23
I got it to build but had to remove a check in the PKGBUILD  it looks promising thank you for finding that package just what I need

**Comment by fancytenseletters** [comment] 2017-12-20 23:08
As for the main topic I think update command can be changed to plain `pacman -Syu` (without `--noconfirm` and `--force` arguments) when Konsole output is chosen which makes more sense to be interactive.

**Comment by I-Dream-in-Code** [comment] 2017-12-21 00:46
@fancytenseletters updated 

I made it multithreaded so it won't freeze the UI when you run checkupdates as well

**Comment by I-Dream-in-Code** [comment] 2017-12-21 12:36
@LittleHuba  Sorry it's taken so long.  Had to finish school.

I looked at GNOME version and his just parses text.  The problem I feel is that there's no way to run purely in the background.  it's just creating a terminal window and updates.

I'm working on a version that upgrades in the background and auto-selects the first alphabetical AUR helper.

selecting and running the aur helper in konsole works just fine.

right now there's just making it run in the background that's the big struggle.

I'll have a lot more time now school's done

**Comment by LittleHuba** [comment] 2018-01-02 16:08
Well updating AUR in background is not really a good idea. It happens quite regular, that there is a bug in the PKGBUILD. That would result in quite the big issue. Additionally you would need to provide the additional information that is required in the update process, like files that are not overwritten and you have to manually update, ...

You might want to redecie if it is the best choice. Arch users are normally not averse to using a console ;) And I for sure would not use software that hinders me in some way (by providing not all information or updating with --force which can kill your whole system)

**Comment by I-Dream-in-Code** [comment] 2018-01-02 16:46
Yeah I removed the --force option

Plus people might need to inspect package build etc

I'll push a console only version and if I get a GitHub issue about background I'll refer them to this issue

**Comment by I-Dream-in-Code** [comment] 2018-01-03 03:04
@LittleHuba I push the changes just now.  AUR is supported and currently in konsole mode only with an option to `--noconfirm`

master and AUR package are updated.

it automatically selects the first alphabetical AUR Helper list in `/usr/bin` so I hope I got the commands right for each individual helper

Let me know how it works and start a new issue for something different so it's easier to manage versus 2 giant issues for multiple things

**Closed by I-Dream-in-Code** 2018-01-03 03:04 UTC
